### ISSUE TITLE
Login need to click twice in the begining

### ISSUE THREAD

**Issue by imrazib** [yhyozturk/Doctor-Appointment-App#40]
First time after registration, login button does nothing. It works on second click. If the app is restarted, same double click is needed.

**Comment by yhyozturk** [comment]
Thanks for the feed back, i already know this issues but i can't find the reason why?

**Comment by ThulaneNcholo** [comment]
Hi good day I'd like to find out how would I register a doctor?

**Comment by yhyozturk** [comment]
@ThulaneNcholo  sorry for the delay becaouse of it was a project i shelved. Only admin register a doctor with "addDoctorPage"
