### ISSUE TITLE
Firestore

### ISSUE THREAD

**Issue by Omar-Harb97** [yhyozturk/Doctor-Appointment-App#43]
Running pod install...                                             10.9s
Xcode build done.                                           38.6s
Configuring the default Firebase app...
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c7127e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff513fbb20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c710bc +[NSException raise:format:] + 188
	3   Runner                              0x0000000102704c1a +[FIRApp configure] + 138
	4   Runner                              0x0000000102c44386 -[FLTCloudFirestorePlugin init] + 214
	5   Runner                              0x0000000102c44184 +[FLTCloudFirestorePlugin registerWithRegistrar:] + 292
	6   Runner                              0x00000001026ffd80 +[GeneratedPluginRegistrant registerWithRegistry:] + 112
	7   Runner                        <…>
Exited

Hello 
Please I need help in firestore configuration .
Cant connect correctly
is there Firebase Auth?

**Comment by yhyozturk** [comment]
@Omar-Harb97  You need your own firebase account, like i specified in the commend lines and at the beginning of the readme file. There isn't Firebase Auth.
