### ISSUE TITLE
How to create Admin?

### ISSUE THREAD

**Issue by 12amansharma** [yhyozturk/Doctor-Appointment-App#44]
How to create admin account?
without admin account we cannot enter a doctor into the database.
Please help

**Comment by yashdevelops** [comment]
@12amansharma did you get it ?

**Comment by yhyozturk** [comment]
@12amansharma @yashdevelops   sory for the delay, I couldn't spare time for this repo from working on other projects. You can't create an admin account, but you can see in "lib/mixins/validation_mixin.dart" line 24. So you can login as admin with username: "admin" , password probably is : "admin" :) and then you can add doctor to database.

String validateAdmin(String value) {
    if (value != "admin") {
      return "Hatalı yada eksik bilgi girdiniz";
    }
    return null;
  }
